# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FunCoFFEE' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FunCoFFEE
    pod 'RxSwift', '5.1.1'
    pod 'RxCocoa', '5.1.1'
    pod 'ObjectMapper', '3.5.2'
    pod 'Moya/RxSwift', '14.0.0'
end
